image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 10 x64
  - npm install

build_script:
  - npm run pack
  - npm run dist

test: off

environment:
  GH_TOKEN:
    secure: nKZ9dCUFltzD3cSiHSSnW5uQLi+cGS3zVJFglq1ocfGEJ5ZmMdHTnSt6ZPNIeZPD

branches:
  only:
    - master
